export const CitySeed = [
  { title: 'Angra dos Reis' },
  { title: 'Aperibé' },
  { title: 'Araruama' },
  { title: 'Areal' },
  { title: 'Armação de Búzios' },
  { title: 'Arraial do Cabo' },
  { title: 'Barra do Piraí' },
  { title: 'Barra Mansa' },
  { title: 'Belford Roxo' },
  { title: 'Bom Jardim' },
  { title: 'Bom Jesus do Itabapoana' },
  { title: 'Cabo Frio' },
  { title: 'Cachoeiras de Macacu' },
  { title: 'Cambuci' },
  { title: 'Campos dos Goytacazes' },
  { title: 'Cantagalo' },
  { title: 'Carapebus' },
  { title: 'Cardoso Moreira' },
  { title: 'Carmo' },
  { title: 'Casimiro de Abreu' },
  { title: 'Comendador Levy Gasparian' },
  { title: 'Conceição de Macabu' },
  { title: 'Cordeiro' },
  { title: 'Duas Barras' },
  { title: 'Duque de Caxias' },
  { title: 'Engenheiro Paulo de Frontin' },
  { title: 'Guapimirim' },
  { title: 'Iguaba Grande' },
  { title: 'Itaboraí' },
  { title: 'Itaguaí' },
  { title: 'Italva' },
  { title: 'Itaocara' },
  { title: 'Itaperuna' },
  { title: 'Itatiaia' },
  { title: 'Japeri' },
  { title: 'Laje do Muriaé' },
  { title: 'Macaé' },
  { title: 'Macuco' },
  { title: 'Magé' },
  { title: 'Mangaratiba' },
  { title: 'Maricá' },
  { title: 'Mendes' },
  { title: 'Mesquita' },
  { title: 'Miguel Pereira' },
  { title: 'Miracema' },
  { title: 'Natividade' },
  { title: 'Nilópolis' },
  { title: 'Niterói' },
  { title: 'Nova Friburgo' },
  { title: 'Nova Iguaçu' },
  { title: 'Paracambi' },
  { title: 'Paraíba do Sul' },
  { title: 'Parati' },
  { title: 'Paty do Alferes' },
  { title: 'Petrópolis' },
  { title: 'Pinheiral' },
  { title: 'Piraí' },
  { title: 'Porciúncula' },
  { title: 'Porto Real' },
  { title: 'Quatis' },
  { title: 'Queimados' },
  { title: 'Quissamã' },
  { title: 'Resende' },
  { title: 'Rio Bonito' },
  { title: 'Rio Claro' },
  { title: 'Rio das Flores' },
  { title: 'Rio das Ostras' },
  { title: 'Rio de Janeiro' },
  { title: 'Santa Maria Madalena' },
  { title: 'Santo Antônio de Pádua' },
  { title: 'São Fidélis' },
  { title: 'São Francisco de Itabapoana' },
  { title: 'São Gonçalo' },
  { title: 'São João da Barra' },
  { title: 'São João de Meriti' },
  { title: 'São José de Ubá' },
  { title: 'São José do Vale do Rio Preto' },
  { title: 'São Pedro da Aldeia' },
  { title: 'São Sebastião do Alto' },
  { title: 'Sapucaia' },
  { title: 'Saquarema' },
  { title: 'Seropédica' },
  { title: 'Silva Jardim' },
  { title: 'Sumidouro' },
  { title: 'Tanguá' },
  { title: 'Teresópolis' },
  { title: 'Trajano de Morais' },
  { title: 'Três Rios' },
  { title: 'Valença' },
  { title: 'Varre-Sai' },
  { title: 'Vassouras' },
  { title: 'Volta Redonda' },
];

export default CitySeed;
